### ISSUE TITLE
Add UglifyJS2

### ISSUE THREAD

**Issue by sijad** [flarum/gulp#2]
UglifyJS2 seems pretty good, it rename local variables too
and can helps to prevent reaching google closure limit
related to flarum/core#887

https://github.com/mishoo/UglifyJS2
https://github.com/terinjokes/gulp-uglify

**Comment by tobyzerner** [comment]
The thing is we want to do our minification with PHP so that you can use/see the full, unminified source when debug mode is on. Google closure compiler limit isn't a problem because we use another service to do that rather than Google's one (with a PHP local minification lib as a backup).

**Comment by tobyzerner** [comment]
Oh, just saw you linked to #887, which is a fair point.

We could consider committing both minified and unminified JS to the repo, so PHP can use whichever one according to debug mode, but it doesn't have to minify itself.

**Comment by franzliedke** [comment]
Don't we have a `--production` flag for gulp? Wouldn't it be enough to simply uglify only in the package built for distribution?

**Comment by franzliedke** [comment]
Oh wait, that doesn't help for extensions, right?

**Comment by tobyzerner** [comment]
No, and also we still want to support doing the current method of installation with Composer even after we are offering a distribution package again.

**Comment by sijad** [comment]
produced source map by uglify isn't enough for debugging in browser?

some reminders:
- http://stackoverflow.com/a/21719713/4774039
- https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Use_a_source_map

**Comment by tobyzerner** [comment]
@sijad

> produced source map by uglify isn't enough for debugging in browser?

What do you mean?

**Comment by sijad** [comment]
with source maps it's possible to debugging minified javascript and less files, it's not necessary to have both minified and unminified file.

**Comment by sijad** [comment]
> We could consider committing both minified and unminified JS to the repo, so PHP can use whichever one according to debug mode, but it doesn't have to minify itself.

minified files + their source maps can do the same.

**Comment by sijad** [comment]
this way no need to implement php debug mode, browser will do the job

**Comment by tobyzerner** [comment]
Ah silly me, very good point! I think this is a great idea then.

**Comment by tobyzerner** [comment]
One potential issue is that we still need to combine minifed JS files together in PHP, because the required JS will vary depending on which extensions are enabled. Are we able to do the same for the source maps (combine individual source maps to reflect the contents of the combined JS file)?

**Comment by sijad** [comment]
I found these
https://github.com/koala-framework/sourcemaps
https://github.com/axypro/sourcemap
but both seem to be old, not sure if they support latest sourcemaps

**Comment by tobyzerner** [comment]
Sweet, good to know that it can be done. Thanks @sijad!

**Comment by sijad** [comment]
it seems easy to be done I guess: https://github.com/axypro/sourcemap/blob/master/doc/concat.md#the-algorithm

**Comment by tobyzerner** [comment]
Moving to flarum/core#1024 since the change affects core, not just flarum-gulp.
